docs/account/adding-huawei-api-key.md
docs/account/slack-notifications.md
docs/build/build-manually-or-with-triggers.md
docs/getting-started-with-appcircle.md
docs/infrastructure/ios-build-infrastructure.md
docs/store-submit/huawei-app-gallery.md
docs/updates/release-notes.md

Huawei AppGallery documentation added

---

docs/account/sso/_category_.json
docs/account/sso/auth-openid.md
docs/account/sso/auth-saml.md
docs/account/sso/azure-saml.md
docs/account/sso/okta-openid.md
docs/account/sso/okta-saml.md
docs/account/sso/onelogin-saml.md
docs/account/sso/single-sign-on.md

SSO documents added

---

docs/account/_category_.json
docs/appcircle-api/_category_.json
docs/best-practices/_category_.json
docs/continuous-testing/_category_.json
docs/emulator-simulator/_category_.json
docs/enterprise-appstore/_category_.json
docs/enterprise-appstore/add-ent-profile.md
docs/enterprise-appstore/configure-ent-profile.md
docs/enterprise-appstore/customize-ent-store.md
docs/environment-variables/_category_.json
docs/infrastructure/_category_.json
docs/integrations/_category_.json
docs/reports/_category_.json
docs/signing-identities/_category_.json
docs/signing-identities/ios-certificates-and-provisioning-profiles.md
docs/store-submit/_category_.json
docs/troubleshooting-faq/_category_.json
docs/updates/_category_.json
docs/workflows/_category_.json

Enterprise Store docs added

---

docs/distribute/create-or-select-a-distribution-profile.md
docs/enterprise-appstore/enterprise-reports.md
docs/integrations/increasing-the-version-number-automatically-for-ios-and-android.md
docs/integrations/managing-release-notes.md
docs/troubleshooting-faq/common-issues.md
docs/updates/release-notes.md
docs/workflows/common-workflow-steps.md

Release 2.9.11

---

docs/account/my-organization.md
docs/environment-variables/appcircle-specific-environment-variables.md
docs/troubleshooting-faq/common-issues.md
docs/updates/release-notes.md
docs/versioning/android-version.md
docs/versioning/ios-version.md
src/components/VersionPlayground.js

- Android Versioning You can manage version code and version name directly with UI.
- Enterprise Store You can change the display picture of your apps.
- Added Open menu to actions list on build profiles.
- Enterprise Store App usage reports update more frequently.
- My Organization Access Management document updated.
- Creating a new branch without a commit was not triggering a build. This is fixed.
- SSO UI issues fixed
- Android Build Tools 31.0.0 corrupted error message fixed.

Release v2.9.12

---

docs/self-hosted-runner/_category_.json
docs/self-hosted-runner/installation.md
docs/self-hosted-runner/manage-pools.md
docs/self-hosted-runner/manage-runners.md
docs/self-hosted-runner/overview.md
docs/self-hosted-runner/runner-service.md
docs/self-hosted-runner/update.md

Checklist to myself before merge:
- https://cdn.appcircle.io < https://storage.googleapis.com/appcircle-dev-common

#AG-77 self-hosted runner docs

---

docs/self-hosted-runner/installation.md
docs/self-hosted-runner/update.md

- Installation and update pages have modifications to clarify some cases.
- Self-hosted runner version is bumped from 1.3.5 to 1.3.6.

#AG-87 self-hosted runner doc updates

---

docs/infrastructure/ios-build-infrastructure.md

I've updated macOS version as `12.5.1` in **iOS Build Infrastructure** page.

#AG-95 Xcode 14 rc updates

---

docs/self-hosted-appcircle/_category_.json
docs/self-hosted-appcircle/installation.md
docs/self-hosted-appcircle/integration.md
docs/self-hosted-appcircle/overview.md

I moved documentation created in linear issue to Appcircle docs.
I added some minor sections. (overview etc.)

#BE-794 Add docs for self-hosted appcircle

---

docs/self-hosted-appcircle/installation.md
docs/self-hosted-appcircle/overview.md

I reviewed and updated installation steps according to latest self-hosted appcircle changes.

#BE-819 Update self-hosted appcircle installation

---

docs/self-hosted-runner/installation.md
docs/self-hosted-runner/update.md

Bump self-hosted runner version from 1.3.7 to 1.3.9

#AG-116 self-hosted runner update

---

docs/continuous-testing/_category_.json
docs/continuous-testing/running-android-unit-tests.md
docs/continuous-testing/running-ios-unit-and-ui-tests.md

Added iOS and Android Test Reports

---

docs/infrastructure/accessing-repositories-in-internal-networks-firewalls.md

I added Teknotel IP block in CIDR notation with related info section.

#AG-144 Add Teknotel IP block for default M1 cloud

---

docs/self-hosted-appcircle/installation.md
docs/self-hosted-runner/installation.md

Self-hosted appcircle docs were improved with given feedbacks. I also added some important but missing sections. I reorganized some sections for better understanding.
There is a list of items in Linear issue which summarizes improvements done. See it for details.

#BE-845 Improve self-hosted appcircle docs

---

docs/self-hosted-appcircle/overview.md

According to latest feedbacks from team, I made some updates to our architecture diagram.
See details in [#BE-935](https://linear.app/appcircle/issue/BE-935/update-self-hosted-appcircle-diagram).

#BE-935 Update self-hosted appcircle overview diagram

---

docs/self-hosted-appcircle/git-providers.md
docs/self-hosted-appcircle/installation.md

I added some extra notes and cautions about `user-secret`in order to clarify configuration process.
I fixed some typos.

#BE-939 Add some notes about user-secret and global.yaml

---

docs/self-hosted-appcircle/git-providers.md
docs/self-hosted-appcircle/installation.md
docs/self-hosted-appcircle/integration.md
docs/self-hosted-appcircle/update.md

I added "update" docs for self-hosted appcircle.
I updated items order in left menu as:
- overview...
- install
- update
- ...

#BE-937 Add update docs for self-hosted appcircle

---

docs/self-hosted-appcircle/installation.md

I rewrote DNS settings section for details of using `/etc/hosts` for both server and client.

#BE-970 Update DNS settings with detailed hosts file usage

---

docs/self-hosted-appcircle/installation.md

Improvements to "Prerequisites" section
- "Supported Linux Distributions" has its own subsection
- "Hardware Requirements" has its own subsection
- Add caution for CPU architecture
- Add info for SSD preference
- Add specs for `test` environments > minimum
- Add specs for `prod` environments > recommended
- Add details on "swap" usage and "swappiness" configuration

#BE-1120 details for self-hosted appcircle hardware requirements

---

docs/self-hosted-appcircle/overview.md

We have a new diagram for self-hosted appcircle. It's more abstract and better in appearance.

#BE-1127 Update self-hosted appcircle diagram

---

docs/self-hosted-appcircle/update.md

Added version command tip to help users find either the self hosted Appcircle runner script or docker images hashes.

#BE-1254 Add tip for version command

---

docs/infrastructure/android-build-infrastructure.md

Os versions and tool package versions updated.

#BE-1314 Updated package and os versions

---

docs/self-hosted-appcircle/installation-podman.md

- Fixed typo on conf file about containers 
- Removed comments from socat systemd services

#BE-1396 Fixed 

---

docs/self-hosted-appcircle/installation-podman.md
docs/self-hosted-appcircle/installation.md

Added information about changing data paths for both docker and podman.

#BE-1406 Container Data Location Guide

---

docs/self-hosted-appcircle/network-access.md
docs/self-hosted-appcircle/overview.md

Added external network domains that needed at self hosted installations and runtime.

#BE-1131 Added Network Access Details

---

docs/self-hosted-appcircle/configure-server/_category_.json
docs/self-hosted-appcircle/configure-server/git-providers.md
docs/self-hosted-appcircle/configure-server/integration.md
docs/self-hosted-appcircle/configure-server/network-access.md
docs/self-hosted-appcircle/configure-server/ssl-configuration.md
docs/self-hosted-appcircle/install-server/_category_.json
docs/self-hosted-appcircle/install-server/docker.md
docs/self-hosted-appcircle/install-server/podman.md
docs/self-hosted-appcircle/overview.md
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/_category_.json
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/android-emulator.md
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/custom-certificates.md
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/manage-pools.md
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/manage-runners.md
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/runner-service.md
docs/self-hosted-appcircle/self-hosted-runner/installation.md
docs/self-hosted-appcircle/self-hosted-runner/overview.md
docs/self-hosted-appcircle/self-hosted-runner/update.md
docs/self-hosted-appcircle/update.md
docs/updates/release-notes.md

I reorganized the whole left navigation as planned in the issue description. I also updated the URLs for the changed file locations.

#BE-1397 Reorg ToC for self-hosted appcircle section

---

docs/account/sso/auth-openid.md
docs/account/sso/auth-saml.md
docs/account/sso/azure-saml.md
docs/account/sso/okta-openid.md
docs/account/sso/okta-saml.md
docs/account/sso/onelogin-saml.md
docs/account/sso/single-sign-on.md
docs/self-hosted-appcircle/configure-server/disable-signup.md

Added page that gives information about disabling signup button. This way, users are enforced to signup with sso or ldap.

#BE-1459 Added disable signup page

---

docs/self-hosted-appcircle/configure-server/network-access.md

Added urls for downloading and installing command line tools for macOS.

#BE-1531 Command Line Tools Urls

---

docs/infrastructure/android-build-infrastructure.md
docs/infrastructure/ios-build-infrastructure.md

Updated iOS _and Android_ infrastructure page with macOS v.13.4.1.

#BE-1517 Infra Pages Updated

---

docs/self-hosted-appcircle/install-server/docker.md

Added infobox for installing docker on RHEL 8.6 and later.

#BE-1407 Added Docker Install Infobox on RHEL 8.6+

---

docs/self-hosted-appcircle/install-server/overview.md
docs/self-hosted-appcircle/install-server/podman.md

Added a page that gives a summary about Appcircle server installation which is not detailed and refers to others pages.

#BE-1519 Server Installation Overview

---

docs/updates/release-notes.md

added the azure integration link for last release note

#BE-1655 Update latest release notes for Azure link

---

docs/troubleshooting-faq/common-issues.md

I added customer approved solution to the react native FAQ page.

#BE-1702 Add yarn solution to FAQ

---

docs/self-hosted-appcircle/configure-server/disable-signup.md

Added a caution about resetting data while disabling signup

#BE-1669 Added a Caution About Resetting Data While Disabling Signup

---

docs/self-hosted-appcircle/install-server/docker.md
docs/self-hosted-appcircle/install-server/podman.md

Removed unnecessary packages from packages title

#BE-1319 Dockerize Export Command | Removed Unnecessary Packages 

---

docs/self-hosted-appcircle/configure-server/proxy-configuration.md

Added a caution where users should be careful.
Automized subdomains so user don't need to do anything extra.

#BE-1631 Added Caution and Automized Subdomains On "No Proxy" Page

---

docs/workflows/common-workflow-steps.md

@csonuryilmaz Aşağıdaki ekran resminin de resimlerin depolandığı yere eklenmesi gerekir doğru çalışabilmesi için:

BE-1873 Updated cache document

---

docs/account/adding-google-play-service-account.md

Following picture must be add with same name: [Archive.zip](https://github.com/appcircleio/appcircle-docusaurus/files/13231763/Archive.zip)
Could you help me? @myalcinkuru

BE-2028 Update Google Service Acount doc

---

docs/self-hosted-appcircle/configure-server/network-access.md
docs/self-hosted-appcircle/configure-server/offline-installation.md

We provided information about load command which is for pulling and loading container images from a single zip file.

#BE-1320 added offline install and update page v2

---

docs/updates/release-notes.md

@csonuryilmaz abi, Improvement alanındaki LDAP brute-force maddesi için @safderun bir pr açmış, bu merge edilirse bunu linkleyebilirim. 
PR => https://github.com/appcircleio/appcircle-docusaurus/pull/217
Ayrıca Feature alanı için iki maddede de linklemeyi dökümanı yarın yazıp yapacağım.

november release note #BE-2250

---

docs/infrastructure/ios-build-infrastructure.md

Update iOS build infrastructure page for new Xcode version.

BE-2371 Add Xcode 15.2.x to Xcode options

---

docs/distribute/downloading-binaries.md
docs/integrations/appdome-integration.md

- Fix the typo reported by @akinihsan :pray: 
- Format and improve titles in Appdome doc

#BE-2490 Improve titles and fix typo

---

docs/infrastructure/android-build-infrastructure.md
docs/infrastructure/ios-build-infrastructure.md

iOS and android build infrastructure pages were updated for latest `Node.js` upgrade.

BE-2280 Update Node.js and NPM version in docs

---

docs/infrastructure/android-build-infrastructure.md
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/android-emulator.md

I added cautions about Android emulator requirement about virtualization support.

BE-1316 Virtualization support for android emulators

---

docs/infrastructure/android-build-infrastructure.md
docs/infrastructure/ios-build-infrastructure.md
docs/self-hosted-appcircle/self-hosted-runner/installation.md

Update tool versions and Ventura -> Sonoma

BE-2118 Update build infrastructure pages

---

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md

- Update macOS image version and MD5
- Add notes about Sonoma stack
- Add info sections for some SSH cases
- Add tip for `appsettings.json`
- Add version suffix to the `run.sh`
- Add Xcode disks to `tart run` commands

BE-2381 BE-2485 Update macOS VM image docs

---

netlify.toml

- SEO-reported links were prioritized.
- Wrong redirection entries were fixed.
- `force=true` was removed from rules.

BE-3044 Fix Netlify redirection rules (part-1)

---

docs/distribute/create-or-select-a-distribution-profile.md

Added a guide for sending apps to publish profile from testing distribution profile with screenshots.

#BE-3110 Docs Update - Send to Publish section Update

---

docs/build/manage-the-connections/manage-the-connections.md

Added Deleting PAT Connections section inside Manage the Connections page of Build Module.

#BE-3112 Docs Update - PAT Connection Remove on the Build Connection Page

---

docs/release-notes.md

Added Release Notes for 3.17.0. May 17 Release.

#BE-3730 Release Notes 3.17.0

---

docs/release-notes.md

Added hyperlinks to a feature announcement on latest release notes.

#BE-3743 Update on Release Notes 3.17.0

---

docs/account/index.md
docs/account/my-organization/team-activity-log.md

Added Team Activity Log section for organizations and added info about it inside organizations and account index.

#BE-3744 Docs Update - Team Activity Log

---

docs/environment-variables/index.md
docs/environment-variables/managing-variables.md
docs/environment-variables/platform-specific-usage/using-environment-variables-in-android-projects.md
docs/environment-variables/platform-specific-usage/using-environment-variables-in-ios-projects.md

Updated Images related to environment variables section.

#BE-3108 Docs Update - Environment Variable Type Field Update

---

docs/release-notes.md

Added release notes for the 3.17.1 hot fix.

#BE-3786 3.17.1 Release Notes

---

docs/distribute/testing-management/downloading-binaries.md

Added new screenshots and tip for testing distribution download page.

#BE-3170 Docs Update - Search and Filter option for Test Dist. in Download Page

---

docs/release-notes.md

Added release notes for 3.18.0 Release.

#BE-3852 3.18.0 Release Notes May 31

---

docs/publish-module/publish-information/marking-release-candidates.md

Added additional info on Release Candidates on Publish.

#BE-3103 Docs Update - Release Candidate Publish Flow Rules

---

docs/self-hosted-appcircle/configure-server/integrations-and-access/ldap-settings.md

Added additional info on LDAP Mapping and sycn. process.

#BE-3779 Docs Update - LDAP Mapping Updates

---

docs/release-notes.md

Added Workflow related updates to release notes 3.18.0.

#BE-3884 Release Notes 3.18.0 Updates

---

docs/release-notes.md

Added Release Notes for 3.19.0 Release. 
Backend Improvement items are not included.
Microsoft Intune links are not available.

#BE-3963 Release Notes 3.19.0

---

docs/release-notes.md

Updates on Release Notes 3.19.0.

#BE-3975 Updates on Release Notes 3.19.0.

---

docs/release-notes.md

Fixes and updates for 3.19 release notes.

#BE-3984 Release Notes 3.19.0 Fixes

---

docs/release-notes.md

#BE-4008 Release Notes 3.19.1

---

docs/account/index.md
docs/account/my-organization/notifications-and-communication/index.md
docs/account/my-organization/notifications-and-communication/teams-notifications.md
docs/account/my-organization/webhooks.md

updated search tags for webhooks and notifications.

#BE-3682 Webhooks - Notifications missing keywords

---

docs/release-notes.md

updates on release note 3.19.1

#BE-4016 Release Notes 3.19.1 Update

---

docs/account/my-organization/team-activity-log.md
docs/account/my-organization/webhooks.md
docs/marketplace/fastlane/enterprise-store/index.md
docs/marketplace/fastlane/testing-distribution/index.md
docs/marketplace/jenkins/enterprise-store/index.md
docs/marketplace/visual-studio-marketplace/testing-distribution/index.md
docs/publish-integrations/common-publish-integrations/custom-script.md
docs/workflows/android-specific-workflow-steps/app-post-processor.md

Updated duplicated descriptions and titles. Added sidebar labels for some titles.

#BE-4012 Documentation SEO Issues [Semrush]

---

README.md

Added screenshot guide and warning regarding title and description setup.

#BE-4019 ReadME Updates

---

docs/release-notes.md

#BE-4041 3.19.1 New Updates

---

docs/build/build-process-management/build-profile-branch-operations.md

Added branch filtering options and screenshots.

#BE-3109 Build Profile Branch List Filter for Build Status

---

docs/account/my-organization/my-organization.md

Updated screenshots, added tip for search bar of team management.

#BE-4072 Docs - Organization Members Search Filter

---

docs/publish-module/binary-management/index.md

Added status filters for publish module

#BE-3106 Publish Profile Filter for Statuses

---

docs/signing-identities/apple-profiles.md

Added provisioning profile multiple upload, multiple delete, and warnings.

BE-4060 Docs - Multiple Provisioning Profile Upload / Delete Update

---

docs/account/my-organization/my-organization.md

Added extra information for organization switching.

#BE-4073 Docs - Switching Organizations Update

---

docs/release-notes.md

added a fresh fix note and updated links for new documentation.

#BE-4083 Release Notes 3.19.1 Update

---

docs/enterprise-appstore/enterprise-app-store-setup/configure-ent-profile.md
docs/enterprise-appstore/enterprise-app-store-setup/customize-ent-store.md

Added sub organization informations for enterprise store.

#BE-4082 Docs - Enterprise Store Updates

---

docs/appcircle-api/index.md

Added Migration Tool info on index.

#BE-4150 Migration Tool Update

---

docs/release-notes.md

#BE-4193 Release Notes Aug 5

---

docs/release-notes.md

#BE-4230 Release Notes Update Aug 7

---

docs/build/platform-build-guides/building-dotnet-maui-apps-with-custom-scripts.md
docs/build/platform-build-guides/index.md

Add documentation about .NET MAUI apps.

BE-4170 .NET MAUI Apps on Appcircle

---

docs/build/platform-build-guides/building-dotnet-maui-apps.md
docs/build/platform-build-guides/index.md
netlify.toml

I implemented suggested SEO changes and added "Next Steps" section to connect journey.

BE-4170 SEO Updates & Next Steps section

---

docs/infrastructure/ios-build-infrastructure.md

✨ We added new Xcode version to the iOS build infrastructure documents.

BE-4268 Add Xcode 16.1 Beta 1

---

docs/release-notes.md
docs/testing-distribution/create-or-select-a-distribution-profile.md
docs/testing-distribution/index.md
docs/testing-distribution/reports/index.md
netlify.toml

#BE-4208 TD Fixes

---

docs/enterprise-app-store/store-settings.md

added none auth type for enterprise, updated screenshots

 #BE-4456 Docs - Enterprise Store Update - None Authentication

---

docs/release-notes.md
docs/testing-distribution/testing-groups.md

#BE-3990 - DOC - LDAP Group for Testing Dist.

---

docs/enterprise-app-store/in-app-updates/index.md

Added extra information regarding retrieving enterprise profile id

#BE-4487 Doc update for in-app update

---

docs/release-notes.md

added release notes for fixes from friday.

#BE-4524 Release Note Update Sep 30

---

docs/enterprise-app-store/enterprise-app-store-profile.md
docs/enterprise-app-store/enterprise-portal.md
docs/enterprise-app-store/enterprise-reports.md
docs/enterprise-app-store/in-app-updates/index.md
docs/enterprise-app-store/index.md
docs/enterprise-app-store/portal-customization.md
docs/enterprise-app-store/portal-settings.md
docs/release-notes.md
docs/self-hosted-appcircle/configure-server/enterprise-store.md
netlify.toml

Updated Enterprise Store related phrases to Enterprise Portal.

#BE-4522 Docs - Enterprise Store to be renamed to Enterprise Portal

---

docs/release-notes.md

additional self hosted fixes for release notes

#BE-4588 Self Hosted Release Notes

---

docs/enterprise-app-store/enterprise-portal.md
docs/testing-distribution/testing-portal.md

added cookie warning for portals

#BE-3676 Cookie enabling requirements is needed to add store / distribution login UIs.

---

docs/account/my-organization/integrations/authentications/store-and-distribution-ldap-authentication.md
docs/account/my-organization/integrations/authentications/store-and-distribution-sso-authentication.md
docs/build/manage-the-connections/adding-a-build-profile/connecting-to-azure.md
docs/continuous-testing/android-testing/index.md
docs/continuous-testing/android-testing/running-android-unit-tests.md
docs/continuous-testing/ios-testing/index.md
docs/marketplace/jenkins/index.md
docs/marketplace/visual-studio-marketplace/index.md
docs/self-hosted-appcircle/configure-server/advanced-configuration/index.md
docs/self-hosted-appcircle/configure-server/integrations-and-access/index.md
docs/self-hosted-appcircle/install-server/cloud-providers/aws.md
docs/self-hosted-appcircle/install-server/cloud-providers/index.md
docs/self-hosted-appcircle/self-hosted-runner/cloud-providers/aws.md
docs/self-hosted-appcircle/self-hosted-runner/cloud-providers/index.md
docs/tags.yml
docs/workflows/android-specific-workflow-steps/android-dependency-report.md
docs/workflows/android-specific-workflow-steps/azure-bot-for-detekt-report.md
docs/workflows/common-workflow-steps/set-environment-variable.md
docs/workflows/common-workflow-steps/upload-files-to-amazon-s3.md
docs/workflows/ios-specific-workflow-steps/carthage.md

#BE-4538 Clean up the Docs tags that isn't defined in tags.yml

---

docs/infrastructure/ios-build-infrastructure.md

✨ We added new Xcode version to the iOS build infrastructure documents.

BE-4674 Add Xcode 16.2 Beta 1

---

docs/infrastructure/ios-build-infrastructure.md
docs/publish-module/publish-settings/index.md

macOS Intel pool retirement documentation updates

BE-4658 Remove retired macOS pool for iOS

---

docs/build/build-process-management/build-profile-configuration.md
docs/build/platform-build-guides/building-android-applications/index.md
docs/build/platform-build-guides/building-dotnet-maui-apps.md
docs/build/platform-build-guides/building-xamarin-apps.md
docs/continuous-testing/android-testing/running-android-unit-tests.md
docs/infrastructure/android-build-infrastructure.md
docs/infrastructure/ios-build-infrastructure.md
docs/publish-module/publish-settings/index.md
docs/release-notes.md
docs/workflows/android-specific-workflow-steps/wait-for-android-emulator.md
docs/workflows/react-native-specific-workflow-steps/react-native-ui-test.md

Updated texts and screenshots in pool selection related areas.

#BE-4818 Pool Name Updates

---

docs/infrastructure/ios-build-infrastructure.md

Bump Xcodeproj version to latest for macOS Sonoma pool

BE-4880 xcodeproj upgrade

---

docs/release-notes.md

#BE-4908 SH Release Note Update

---

docs/build/platform-build-guides/building-android-applications/index.md
docs/infrastructure/android-build-infrastructure.md
docs/infrastructure/ios-build-infrastructure.md
docs/self-hosted-appcircle/self-hosted-runner/configure-runner/custom-certificates.md
docs/workflows/common-workflow-steps/custom-script.md
docs/workflows/react-native-specific-workflow-steps/react-native-ui-test.md

Update Java/JDK version for Android infra

BE-4936 Bump default JDK from 11 to 17

---

docs/appcircle-api-and-cli/api-authentication.md

#BE-5035 Update API Authentication page

---

docs/infrastructure/ios-build-infrastructure.md

Update the build number for the latest Xcode 16.2 release.

BE-4782 Xcode 16.2

---

docs/self-hosted-appcircle/install-server/helm-chart/upgrades.md
docs/self-hosted-appcircle/install-server/linux-package/update.md

BE-5489 Add version caution for OpenShift support

---

docs/release-notes.md
docs/self-hosted-appcircle/index.md

- Add tags
- Change titles
- Add OpenShift text
- Improve texts
- Add K8s/OCP diagram

BE-5525 Update self-hosted overview page

---

docs/self-hosted-appcircle/install-server/linux-package/update.md

Update version history table after GA release.

Update docker/podman self-hosted server version history

---

docs/self-hosted-appcircle/install-server/helm-chart/configuration/production-readiness/database-and-vault.md

PR has changes to make it compatible with the statement below:
> Gönderen: Osman Kibar
> Gönderildi: 14 Ocak 2025 Salı 15:17
> 
> Mongo Database (4.2 ile 8(latest) arasında versiyonları destekliyoruz. İlerki sürümlerde 4.2'ye support vermeyi durdurabiliriz.)

BE-6607 Fix supported MongoDB versions for Helm chart
