docs/workflows/common-workflow-steps.md
I added "cache push" and "cache pull" sections to [common workflow steps](https://docs.appcircle.io/workflows/common-workflow-steps) docs page.
Since all project types have cache push and pull step, I added to "common" section. Given information about cache is applicable to all types of projects.
---
~~**Note:** By now, I'm not sure about periodic removal feature of caches. (Is in production or not?) I've asked team member and waiting for reply. There may be a minor update after reply. cc/ @tosbaha~~
=> Add docs for cache push and pull to workflow steps

docs/infrastructure/ios-build-infrastructure.md
I've edited iOS build infrastructure doc according to latest macOS Monterey changes.
- Add missing Xcode versions to doc
- Update patch version of Catalina
- Update minor version of Monterey
- Update package versions table
- Fix other minor typos in text
=> #AG-76 bump monterey from 12.2.1 to 12.4

docs/account/adding-an-app-store-connect-api-key.md, docs/account/adding-google-play-service-account.md, docs/account/adding-huawei-api-key.md, docs/account/artifacts.md, docs/account/my-organization.md, docs/account/slack-notifications.md, docs/integrations/increasing-the-version-number-automatically-for-ios-and-android.md, docs/integrations/working-with-custom-scripts/custom-script-samples.md, docs/signing-identities/ios-certificates-and-provisioning-profiles.md, docs/updates/release-notes.md, docs/workflows/common-workflow-steps.md
- [Self-Hosted Runners](../self-hosted-runner/overview.md) Self-hosted runner enables you to use your own systems and infrastructure for running Appcircle build pipelines. 
- [Automatic iOS Code Signing](../signing-identities/ios-certificates-and-provisioning-profiles.md) If you're using Xcode 13 or later, you can now use the automatic code signing option to automatically sign your iOS apps.
- [Artifacts Management](../account/artifacts.md) You can set the retention period for your build artifacts.
- [SonarQube Component](../workflows/common-workflow-steps.md) You can use SonarQube for iOS and Android projects.
- Slack messages updated to include store name and distribution links.
- Android v2 signing support improved.
- `Get help with build errors` link fixed.
- Renaming build profiles …
=> Release v2.9.13

docs/self-hosted-runner/android-emulator.md, docs/self-hosted-runner/installation.md, docs/self-hosted-runner/update.md, docusaurus.config.js
I've added "android emulators" page to self-hosted runner in order to explain some system requirements for emulators. That page also gives information about default installed emulator and how to install additional emulators.
I've updated "self-hosted runner update" page which includes extra step for reconfiguration of runner.
I've bumped self-hosted runner version to latest.
=> #AG-89 android emulator

docs/infrastructure/accessing-repositories-in-internal-networks-firewalls.md
All `m1` cloud runners have same outbound IP which should be whitelisted on customer-side if necessary.
=> #AG-112 Add m1 cloud outbound IP

docs/infrastructure/ios-build-infrastructure.md
- Remove catalina from ios build infrastructure
- Remove xcode 11.0 - 12.4 from available list
- Add latest Xcode 14.1.x to xcodes list
=> #AG-119 Update ios build infrastructure

docs/best-practices/onboarding.md, docs/infrastructure/accessing-repositories-in-internal-networks-firewalls.md
I added OVHcloud dedicated server external IP for firewall white-listing. It's used for android agents.
=> #AG-134 OVHcloud android agent IP

docs/self-hosted-appcircle/git-providers.md, docs/self-hosted-appcircle/installation.md
I added "git providers" page to self-hosted appcircle docs to explain below topics.
- how to add "Connect via SSH" option
- how to add "Connect to a Public Repository" option
- how to apply these changes especially after install
=> #BE-850 Add git providers page to self-hosted appcircle

docs/infrastructure/ios-build-infrastructure.md
- added Xcode `14.2.x` to available Xcode versions
- removed tip section (it was meaningful when catalina times)
- moved "Available Xcode Versions" to an upper location
- added monterey versions based on "config" pool selection
=> #AG-148 Add 14.2.x to available Xcode versions

docs/self-hosted-appcircle/ssl-configuration.md
I added a dedicated section for HTTPS configuration of self-hosted appcircle.
It tells HTTPS configuration for "main domain". It shows a working sample from our sample scenario.
Also enterprise app store HTTPS settings are included in the same page.
=> #BE-936 SSL configuration for self-hosted appcircle

docs/self-hosted-appcircle/installation.md
Below topics added to docs:
- docker engine installation vs. snap
- up-to-date ports (removed vault)
- password policy for initial password
=> #BE-962 Update self-hosted appcircle docs

docs/self-hosted-appcircle/installation.md
I added a caution about **vault** service under `docker compose ps` SS.
User should check its status and make sure it's healthy.
Its main message is;
> Before starting to use self-hosted appcircle server, vault service status must be `healthy`.
=> #BE-973 Add caution for vault service status

docs/self-hosted-appcircle/installation.md, docs/self-hosted-appcircle/update.md
It's an important milestone for self-hosted appcircle server. :smile: 
I changed `curl` in order to keep it short and bumped `.zip` package version.
=> #BE-997 Bump self-hosted appcircle version to 3.0.0

docs/self-hosted-appcircle/git-providers.md, docs/self-hosted-appcircle/installation.md, docs/self-hosted-appcircle/overview.md, docs/self-hosted-appcircle/update.md, docs/self-hosted-runner/installation.md, docs/self-hosted-runner/update.md
Latest updates to keep compatibility with `3.1.0` release:
- Update self-hosted appcircle diagram for store submit changes
- Bump self-hosted appcircle version to `3.1.0`
- Update project export commands w/ `export` arg
- Bump self-hosted runner version to `1.3.11`
- Refactor self-hosted runner download command
=> #BE-1127 Update docs for 3.1.0

docs/self-hosted-appcircle/self-hosted-runner/installation.md
We have a PDF file which has details on how to use Appcircle macOS VM image and self-hosted runner it has.
Table of Contents:
- into (reasons to choose VM image)
- requirements (homebrew, tart `0.38.0`)
- getting VM image from Appcircle
- creating base images for 2 runners
- operating there runners (start, stop)
- updating images to persist custom conf.
- troubleshooting guide
Troubleshooting section contains all experiences we got from previous enterprise installations.
___
**Note:** Markdown format is located in https://github.com/appcircleio/ac-script-agent/pull/6
To update PDF our workflow should be,
- Modify markdown file
- Push markdown file
- Export markdown as pdf
- Use git short-SHA in pdf name
- Upload pdf to CDN assets
- Update pdf URL in "tip" section
=> #BE-1107 Add tip section for macOS VM

docs/self-hosted-appcircle/installation.md
Fixed bug in sample script where last line of file was not being read. 
To fix the issue, I updated the script to ensure that it always reads in the last line of the file, even if there is no newline character at the end of the file.
=> #BE-1250 fixed loop end of line issue

docs/infrastructure/ios-build-infrastructure.md
iOS Build infrastructure page updated for Xcode version cautions and macOS packages. 
But there is a problem about maven (not installed) and sdk (was not able to get version)
=> #BE-1206 Updated package versions of macOS for iOS page

docs/self-hosted-appcircle/self-hosted-runner/installation.md
- Bump the macOS VM image version from `macOS_230309` to `macOS_230510`. (Monterey -> Ventura)
- Update relevant sections for the latest macOS VM image (commands, outputs, etc.).
- Add information about packaged Xcode versions and URLs to build infrastructure pages.
=> #BE-1298 Update macOS VM image in runner docs

docs/self-hosted-appcircle/installation.md
Added a small section below the mirroring Appcircle images about using nexus repository as proxy repository.
Screenshots has not been placed because waiting for small images feature.
=> #BE-1269 Added section about nexus proxy

docs/self-hosted-appcircle/update.md
Removed minimum required docker compose version for ` ./ac-self-hosted.sh -n "spacetech" version` command.
=> #BE-1267 Removed minimum docker compose version

docs/self-hosted-appcircle/self-hosted-runner/installation.md
Updated default Xcode version to 14.2 on runner installation iOS section. If users don't provide a Xcode version on runner installation, 14.2 will be installed by default on the runner.
=> #BE-1183 Updated default Xcode version to 14.2

docs/self-hosted-appcircle/git-providers.md, docs/self-hosted-appcircle/installation.md, docs/self-hosted-appcircle/overview.md, docs/self-hosted-appcircle/self-hosted-runner/custom-certificates.md, docs/self-hosted-appcircle/self-hosted-runner/manage-pools.md, docs/self-hosted-appcircle/self-hosted-runner/manage-runners.md, docs/self-hosted-appcircle/ssl-configuration.md, docs/self-hosted-appcircle/update.md
- Some spells fixed
- "appcircle" words uppercased
- Removed unused settings from example yaml
- Added hosts file location for windows, macOS and linux
- Added info about converting pkcs formatted certs to pem format
=> #BE-964 improved self-hosted documents

docs/environment-variables/appcircle-specific-environment-variables.md, docs/integrations/working-with-custom-scripts/custom-script-samples.md, docs/self-hosted-appcircle/self-hosted-runner/installation.md
- Add OpenJDK 17 to available JDK list
- Update "Changing JAVA version" w/ 17
- Add `JAVA_HOME_17_X64` to env vars
___
- Bump macOS VM docs version to `macOS_230606`
=> #BE-1315 Add OpenJDK 17

docs/self-hosted-appcircle/configure-server/ssl-configuration.md
Added 3 commands for converting a pfx (.p12) formatted cert to pem. 
You can remove the password while converting or leave the key password protected.
=> #BE-1583 Added PFX to Pem Info

docs/self-hosted-appcircle/configure-server/proxy-configuration.md
Added *Proxy Configuration* page for describing how to configure proxy settings for the Appcircle server so that Appcircle containers can reach to resources on the internet.
=> #BE-1487 Proxy Configuration Page

docs/self-hosted-appcircle/configure-server/ldap-settings.md
Added page for configuring LDAP lookup decision settings. 
Users now can login with same username with multiple passwords with multiple LDAP settings.
=> #BE-1614 LDAP Lookup Decision Settings Page

docs/infrastructure/android-build-infrastructure.md, docs/troubleshooting-faq/common-issues.md
I updated the Android build infrastructure page:
- Add Intel deprecation note
- 👆 We're trying to push customers to M1 pool.
- Add JDK home paths by pool
- 👆 User doesn't need to run pipeline to get values.
I added FAQ entry: **How can I change the JDK version for autofill?**
We have two options. I tested both options with the sample app below:
- https://github.com/csonuryilmaz/appcircle-sample-android/tree/feature/gradle8-no-home
- You can test '2. Change `JAVA_HOME` using environment variables' option 👆 
- https://github.com/csonuryilmaz/appcircle-sample-android/tree/feature/gradle8
- You can test '1. Change `JAVA_HOME` using `gradle.properties`' option 👆
=> #BE-1625 Add Java FAQ entry for autofill

docs/self-hosted-appcircle/configure-server/proxy-configuration.md
Removed the no proxy shell script that creates no_proxy values due to added to helper-tools directory of ac-script-self-hosted.
=> #BE-1769 Removed no-proxy Shell Script From The Doc Page

docs/self-hosted-appcircle/self-hosted-runner/installation.md, docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md, src/css/custom.css
Added the vm installation page to the Docusaurus as private page which is not listed in sidebar. 
Page is only accessible with direct url. 
Green tip box now forwards to the that private page.
=> #BE-1791 Added macOS Runner vm Installation Page

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
We have a new macOS image version: `macOS_230921`
:warning:  Now it requires a Ventura host. Monterey hosts are not supported.
=> BE-1456 Update MacOS VM Image

docs/self-hosted-appcircle/self-hosted-runner/configure-runner/custom-certificates.md
Removed curl command that downloads the install script.
Also removed the NodeJs warning because we install the cert to NodeJs by default.
=> #BE-1795 Removed Curl Command That Downloads The Install Script

docs/self-hosted-appcircle/self-hosted-runner/configure-runner/custom-certificates.md, docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
Self signed certificates page now includes a guide on how users can use the install cert script manually by providing root ca.
=> #BE-1633 Added Guide For Manual Usage Install Cert Script

docs/infrastructure/android-build-infrastructure.md, docs/infrastructure/ios-build-infrastructure.md
- MacOS version was bumped to `12.5.2` for Ventura.
- Self-hosted runner section was moved to the end of page.
- Fix typos and titles
- Improve formatting
- Update tool versions
=> BE-2008 Update macOS build environment (ios & android)

docs/build/build-profile-configuration.md, docs/build/building-react-native-applications.md, docs/self-hosted-appcircle/faq.md, docs/self-hosted-appcircle/self-hosted-runner/installation.md, docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md, docs/updates/release-notes.md, package.json, yarn.lock
Note: It would be awesome if we could add this to deploy steps. Currently, developers have to manually launch this. Our options:
1. Add to the e.g. `yarn build` step like `build: "docusaurus build && yarn check-broken-links"`
2. Add as a separate step. Note that it should be **AFTER** the build step since it checks for HTML content.
=> feature(BE-2071): Add a tool for broken links and fix them using the tool

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
I updated macOS VM image to the latest version. `230921` > `231218`
Also documentation has some extra updates for the new type of VM image.
=> BE-2404 Update macOS VM image to 231812

docs/infrastructure/android-build-infrastructure.md, docs/infrastructure/ios-build-infrastructure.md, docs/integrations/working-with-custom-scripts/custom-script-samples.md, docs/troubleshooting-faq/common-issues.md
PR includes changes for the latest  JDK upgrades in the runner environment.
It also has a new "info" section that explains how to change the system `java` version for other 3rd party tools.
=> BE-2755 JDK updates | sdkman usage for system java

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
We have a new macOS image which replaces Xcode `15.3` beta-3 with rc-1 .
=> BE-2849 Update macOS VM image version

docs/self-hosted-appcircle/configure-server/appcircle-cli.md, docs/workflows/ios-specific-workflow-steps/index.md
- Rename Appcircle CLI self-hosted configuration docs title
- Fix broken Tuist link in step docs
=> Fix latest feedbacks from CSM team

docs/publish-module/send-to-huawei.md, netlify.toml
Below are the SEO reported links:
- https://docs.appcircle.io/store-submit/apple-app-store
- https://docs.appcircle.io/adding-a-build-profile/connecting-to-private-repository-via-ssh
- https://docs.appcircle.io/build-manually-or-with-triggers
- https://docs.appcircle.io/integrations/custom-script-faq
- https://docs.appcircle.io/integrations/custom-script-samples
- https://docs.appcircle.io/build/build-profile-configuration (not a broken link!)
- https://docs.appcircle.io/distribute/create-or-select-a-distribution-profile.md
- https://docs.appcircle.io/building-multiple-apps-in-one-profile
=> Redirect rules for broken links

docs/self-hosted-appcircle/self-hosted-runner/index.md
> **Differences Between Appcircle-hosted and Self-hosted Runners**
> _Appcircle-hosted runners:_
> - Provides a clean, isolated instance for every build job
> ...
>
> _Self-hosted runners:_
> - Don't need to have a clean instance for every build job (reusable caches)
---
:question: Mete: 
> ... eğer müşteri self – hosted kullanırsa biz isolasyon yapmıyoruz gibi bir anlam çıkmıyor mu?
I removed the "isolation" from the table since it should only have differences between cloud and self-hosted runners. Both supported features are out of scope for this section.
=> BE-2904 Remove isolation from differences table

docs/enterprise-appstore/enterprise-app-store-setup/configure-ent-profile.md, docs/workflows/android-specific-workflow-steps/build-and-test/android-build-for-ui-testing.md, docs/workflows/android-specific-workflow-steps/build-and-test/lint.md
List items should be seperated from `:::` with leading and trailing lines. [ref](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md032---lists-should-be-surrounded-by-blank-lines)
Formatter behaviour is OK for this case. Fixed `:::`.
=> Fix broken docusaurus info boxes

docs/infrastructure/ios-build-infrastructure.md, docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
`15.4.x` was added to the Xcode list, and macOS VM image documentation was improved to have multiple image versions.
=> BE-3129 Update macOS VM image docs - 240417

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
I'm creating this PR on behalf of Cirrus Labs, Inc. (the authors of [Tart](https://github.com/cirruslabs/tart)). We really appreciate that you found Tart useful and it helps your users.
We found that documentation around Tart on https://docs.appcircle.io/ might be misleading and one can affiliate Tart with Appcircle. To clear things up we propose to add a note that [Tart is a registered trademark of Cirrus Labs, Inc](https://tsdr.uspto.gov/#caseNumber=97892370&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch).
=> Add Tart trademark note

docs/infrastructure/ios-build-infrastructure.md, docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
We replaced the release candidate with the latest release of Xcode. So, 
- iOS build infrastructure page got update. (Xcode 15.4)
- macOS VM image version bumped to `240514`. (default)
=> BE-3711 Xcode 15.4 final release updates

docs/distribute/create-or-select-a-distribution-profile.md
Added tip section inside create or select a distribution profile page regarding AAB to APK conversion. Also, changed the Info message to Caution type beneath.
=> Feature/BE-3167 Docs Update - AAB to APK on Testing Distribution page

docs/release-notes.md
3.17.0 release note updates related to self hosted improvement and fixes. Also, added a link for team activity log.
=> #BE-3763 Release Note 3.17.0 Self Hosted Updates

docs/account/my-organization/notifications-and-communication/slack/slack-notifications.md
Updated 2 image URLs due to them having space within their names. Other necessary images were overwritten directly from cloud.
=> #BE-3113 Docs Update - Notification Icon and Message Content Improvement

docs/publish-module/publish-information/delete.md, docs/publish-module/publish-information/download.md, docs/publish-module/publish-information/history.md, docs/publish-module/publish-information/index.md, docs/publish-module/publish-information/marking-release-candidates.md, docs/publish-module/publish-information/meta-data-information.md, docs/publish-module/publish-information/resign-binary.md
Re-named Publish History sub-section to History. 
Publish and Resign History are now merged under History button. 
Updated screenshots throughout the Publish module documentations to have the latest History button. 
Also added additional information inside the History section.
=> #BE-3857 Docs Update - Resign and Publish history Merging

docs/infrastructure/android-build-infrastructure.md, docs/infrastructure/ios-build-infrastructure.md
After the macOS 14.5 migration, some tools were bumped along with Xcode 16.0 Beta 1.
=> BE-2903 Update build stack docs

docs/infrastructure/ios-build-infrastructure.md
=> BE-3958 Xcode 16.0 Beta 2

docs/infrastructure/ios-build-infrastructure.md
=> BE-4032 Xcode 16.0 Beta 3

docs/infrastructure/ios-build-infrastructure.md
=> BE-4113 Xcode 16.0 Beta 4

docs/infrastructure/ios-build-infrastructure.md
=> BE-4214 Update Xcode 16.0 Beta 5

docs/infrastructure/ios-build-infrastructure.md
=> BE-4314 Update Xcode 16.0 build number

docs/self-hosted-appcircle/index.md
In order to clarify that the Appcircle has two types of architecture, we added a title for the previous basic architecture.
Common parts are moved to the "overview" section and added an extra explanation to the "standalone" architecture.
=> Improve self-hosted Appcircle overview page

docs/infrastructure/ios-build-infrastructure.md
=> BE-4420 Update Xcode 16.0 RC 1

docs/infrastructure/ios-build-infrastructure.md
=> BE-4451 Update Xcode 16.0 Release

docs/infrastructure/ios-build-infrastructure.md
Update the build number for the latest Xcode 16.1 in production.
=> BE-4461 Update Xcode 16.1 Beta 2

docs/_need-help.mdx
I added some filtering to the Algolia record extractor to remove unnecessary (noisy) records to be indexed. So, the user can reach more relevant results while searching.
Within this PR, I marked parts of the **Need Help** section in order to exclude them on the Algolia side. By this way, it can be identified from other searchable contexts.
Currently, the "need-help" CSS class is a non-existing class. It can also be used to style the relevant parts in the future. (optional)
=> BE-4394 Mark need help section to exclude

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
I added a new tab that has the `latest` macOS VM image that's used in Appcircle Cloud.
=> BE-4479 Update macOS VM image documents for latest Xcode

docs/account/my-organization/profile-and-team/role-management.md
moved permissions to signing identity from Testing Dist.
=> #BE-4551 Documentation Update for Signing Identity Devices Roles

docs/infrastructure/ios-build-infrastructure.md
Update the build number for the latest Xcode 16.1 in production.
=> BE-4571 Update Xcode 16.1 Beta 3

docs/infrastructure/ios-build-infrastructure.md
Update the build number for the latest Xcode 16.1 in production.
=> BE-4622 Update Xcode 16.1 RC 1

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md, docs/self-hosted-appcircle/update.md
- Add `3.23.2` to the version history
- Fix whitespace bug reported in [BE-4986](https://linear.app/appcircle/issue/BE-4986/tart-vm-run-command-multiline-problem)
=> Self-hosted server hotfix release 3.23.2

docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
Since we modified Xcode `16.0.x - 16.2.x` in the Appcircle Cloud, we deployed the same changes to the relevant self-hosted archives, which required us to update their md5sum info in the document.
=> BE-6417 Change md5sum for modified Xcode packages

docs/self-hosted-appcircle/self-hosted-runner/cloud-providers/aws.md, docs/self-hosted-appcircle/self-hosted-runner/installation.md, docs/self-hosted-appcircle/self-hosted-runner/update.md
Fixes missing runner version update in docs that should have been done previously.
- https://github.com/appcircleio/ac-runner-setup/commits/main/
=> Bump runner version to 1.8.1

docs/self-hosted-appcircle/self-hosted-runner/cloud-providers/aws.md, docs/self-hosted-appcircle/self-hosted-runner/installation.md, docs/self-hosted-appcircle/self-hosted-runner/update.md
There is nothing new as a feature or bug fix. Runner is repackaged to update its workflow step caches for a better cache hit ratio.
=> Bump runner version to 1.8.2
